Vagrant.configure("2") do |config|
config.vm.define :streama do |streama|
streama.vm.box = "bento/centos-7.9"
streama.vm.network :private_network, ip: "192.168.20.4"
streama.vm.hostname = "streama"
streama.vm.provision "shell", path: "./ScriptStreama.sh"
end

config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7.9"
firewall.vm.network "public_network", use_dhcp_assigned_default_route: true
firewall.vm.network :private_network, ip: "192.168.20.5"
firewall.vm.network :forwarded_port, guest: 80, host: 8080
firewall.vm.hostname = "firewall"
firewall.vm.provision "shell", path: "./ScriptFirewall.sh"
end

end